---

extends: stylelint-config-standard

rules:
  max-nesting-depth: 2
  no-unknown-animations: true

  rule-empty-line-before:
    - always
    - except: ['after-single-line-comment', 'first-nested']

  import-notation: url
  selector-type-case: lower
  value-keyword-case: lower
  font-family-name-quotes: always-where-recommended
  color-function-notation: legacy
  alpha-value-notation: number
  custom-property-empty-line-before: never
  media-feature-range-notation: prefix

  comment-empty-line-before:
    - always
    - except: ['first-nested']

  comment-whitespace-inside: always
  comment-word-disallowed-list: ['TODO', 'FIXME']

  # Remove these rules eventually, see https://scuttle.atlassian.net/browse/TT-56
  property-no-vendor-prefix: null
  value-no-vendor-prefix: null
  at-rule-no-vendor-prefix: null

  # Disable this rule for now, it produces hundreds of incidents
  # and would require significant refactoring to resolve.
  no-descending-specificity: null
