name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Deploy CSS
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: ./build.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

      - name: Deploy (GitHub Pages)
        uses: actions/deploy-pages@v4
        id: deployment
